### ISSUE TITLE
undefined method `build' for an instance of Google::Protobuf::DescriptorPool (NoMethodError)

### ISSUE THREAD

**Issue by ukd1** [coinbase/temporal-ruby#313]
Using 0d3a8bb9037d I get the following error:

```bash
/Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/temporal-ruby-0d3a8bb9037d/lib/gen/dependencies/gogoproto/gogo_pb.rb:8:in `<main>': undefined method `build' for an instance of Google::Protobuf::DescriptorPool (NoMethodError)

Google::Protobuf::DescriptorPool.generated_pool.build do
                                               ^^^^^^
	from /Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/russ/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/bundler/gems/temporal-ruby-0d3a8bb9037d/lib/gen/temporal/api/filter/v1/message_pb.rb:7:in `<main>'
```

```bash
% brew search protobuf
==> Formulae
protobuf ✔                          protobuf-c ✔                        protobuf@21                         protobuf@3                          swift-protobuf

==> Casks
protopie


russ@hai-lulzz-6 rails-app % brew info protobuf
==> protobuf: stable 27.1 (bottled)
Protocol buffers (Google's data interchange format)
https://protobuf.dev/
Installed
/opt/homebrew/Cellar/protobuf/27.1 (430 files, 14.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-06 at 09:32:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/protobuf.rb
License: BSD-3-Clause
==> Dependencies
Build: cmake ✔, googletest ✘
Required: abseil ✔
==> Caveats
Emacs Lisp files have been installed to:
  /opt/homebrew/share/emacs/site-lisp/protobuf
==> Analytics
install: 65,632 (30 days), 186,459 (90 days), 714,851 (365 days)
install-on-request: 30,519 (30 days), 86,145 (90 days), 337,904 (365 days)
build-error: 319 (30 days)


russ@hai-lulzz-6 rails-app % brew info protobuf-c
==> protobuf-c: stable 1.5.0 (bottled), HEAD
Protocol buffers library
https://github.com/protobuf-c/protobuf-c
Installed
/opt/homebrew/Cellar/protobuf-c/1.5.0_6 (15 files, 522.9KB) *
  Poured from bottle using the formulae.brew.sh API on 2024-08-06 at 09:32:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/protobuf-c.rb
License: BSD-2-Clause
==> Dependencies
Build: pkg-config ✔
Required: abseil ✔, protobuf ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 5,803 (30 days), 16,589 (90 days), 69,602 (365 days)
install-on-request: 1,149 (30 days), 3,364 (90 days), 14,972 (365 days)
build-error: 10 (30 days)


russ@hai-lulzz-6 rails-app % ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin24]
```

**Comment by ukd1** [comment]
Forcing an old `google-protobuf` - found [in your Gemfile](https://github.com/coinbase/temporal-ruby/blob/0d3a8bb9037d4b736172b8afcbe6dbe65edb7cf8/Gemfile#L2C1-L3C33) seems to have solved this. If this is required, can this be added to the docs to save wasting folks time?

```ruby
gem 'temporal-ruby', github: 'coinbase/temporal-ruby'
gem 'google-protobuf', '~> 3.19'
```

**Comment by tin-ngo-kaligo** [comment]
I faced same issue. Could we update to support newer version for google-protobuf?
